config/routes.rb
Strippekaar::Application.routes.draw do

  get "user/index"
  
  resources :clients

  devise_for :users, :path_names => {:sign_in => 'login'}
  
  match 'users' => 'user#index'

  root :to => "user#index"
  

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Client < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  role                   :string(255)
#

class User < ActiveRecord::Base
  
  belongs_to :client
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end
  
  def new
    @client = Client.new
  end
  
  def create
    @client = Client.new(params[:client])
    
    if @client.save
      redirect_to @client,
        :notice => "Client has been created"
    else
       render :action => "new"
    end
  end
  
  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to root_path,
      :notice => "Client has been destroyed"
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/clients/index.html.haml
%h1 Clients
%p
  = link_to 'Add new client', new_client_path

-if @clients
  %ul
    -@clients.each do |client|
      %li= client.name

app/views/clients/new.html.haml
%h1 New client

= form_for @client do |f|
  = f.label :name
  = f.text_field :name
  
  = f.submit

app/views/clients/show.html.haml
%h1= @client.name

-if @client.users.size > 0
  %ul
    -@client.users.each do |user|
      %li= user.login

%p
  = link_to 'Add new user', new_user_registration_path

%p
  = link_to 'Delete client', client_path, :confirm => 'Are you sure?', :method => :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Strippekaar
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
      
  %body
    %p{ :class => "notice" }
      = notice
    %p{ :class => "alert" }
      = alert
    = yield

app/views/user/index.html.haml
%h1 Users
%p
  = link_to 'Create a user', new_user_registration_path